### ISSUE TITLE
Can't import from node

### ISSUE THREAD

**Issue by saeta-eth** [manuelhe/random-avatar-generator#12] opened 2021-09-05 02:02 UTC
Hi there.

I have tried to use this library from node but an error appears when trying to import it.

> Error: Cannot find module '@fractalsoftware/random-avatar-generator'

Do you know why? Thanks.

**Comment by bobrom** [comment] 2021-11-06 18:47
Hi

You may use my fork as a workaround until the issue is resolved in the main package: https://github.com/bobrom/random-avatar-generator

1. Install the library like this:
`yarn add https://github.com/bobrom/random-avatar-generator.git#1.0.8`

2. Then use it as usual _(both, require and import syntaxes should work)_, i.e.:
`
import { getRandomAvatar } from '@bobrom/random-avatar-generator';
`

**Comment by manuelhe** [comment] 2021-11-08 21:59
Hi! Thank you for your input. Finally, I had some time to upgrade dependencies and workflow. Now the distributed package is quite small and compatible with Node and Browser environments. Latest release v1.0.11 closes this issue: https://github.com/fractalsoftware/random-avatar-generator/releases/tag/v1.0.11

Also, the documentation was updated in order to reflect the correct way to import this library in Node.

**Closed as completed by manuelhe** 2021-11-08 21:59 UTC
Labels: bug
